server:
  port: 8081

api:
  exercise-service:
    base-url: http://localhost:3000
  workout-service:
    base-url: http://localhost:3001

---
spring.config.activate.on-profile: docker

server:
  port: 8080

api:
  exercise-service:
    base-url: http://exercise-service:3000
  workout-service:
    base-url: http://workout-service:3000
